#!/bin/bash
# shell safe code (https://sipb.mit.edu/doc/safe-shell/)
set -eu -o pipefail ; shopt -s failglob

set -e
set -x

if [ "$1" = "--install" ]; then
  mkdir -p $HOME/tools/textadeptx
  cd $HOME/tools
  wget https://foicica.com/textadept/download/textadept_LATEST.x86_64.tgz
  tar zxvf textadept_LATEST.x86_64.tgz
  rm textadept_LATEST.x86_64.tgz
  extr_ta_dir=$PWD/textadept_*.x86_64
  [ -f $extr_ta_dir/textadept-curses ] || { echo "check tools directory. need only one textadept*/textadept-turses"; exit 1; }
  rm -f textadept
  ln -s $extr_ta_dir textadept
else
  echo "--install not specified,so not installing"
fi

echo "selecting"
TADIR=~/tools/textadept
[ -f $TADIR/textadept-curses ] || { echo "Not installed in proper way! check $TADIR!"; exit 1;}
sudo rm -f /usr/bin/tag /usr/bin/ta
sudo ln -s $TADIR/textadept /usr/bin/tag
sudo ln -s $TADIR/textadept-curses /usr/bin/ta
echo "check ta and tag:"
ls -l /usr/bin/ta* # check
sudo update-alternatives --install /usr/bin/editor editor /usr/bin/ta 90 
#sudo update-alternatives --config editor # check
sudo update-alternatives --set editor /usr/bin/ta
echo "select ta:"
#select-editor # select /usr/bin/ta
cat << EOF > $HOME/.selected_editor
# generated by textadept_select.sh from https://github.com/al-zatv/textadept_init
SELECTED_EDITOR="/usr/bin/ta"
EOF